### ISSUE TITLE
Some form tests randomely fails on travis due to some cached locale issue

### ISSUE THREAD

**Issue by swistakm** [bread-and-pepper/django-userena#446]
Is it dutch?
```
======================================================================
FAIL: test_signin_form (userena.tests.tests_forms.AuthenticationFormTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bread-and-pepper/django-userena/userena/tests/tests_forms.py", line 99, in test_signin_form
    invalid_dict['error'][1])
AssertionError: [u'Vul alsjeblieft een correcte gebruikersnaam of e-mailadres in gecombineerd met je wachtwoord.'] != [u'Please enter a correct username or email and password. Note that both fields are case-sensitive.']
======================================================================
FAIL: test_change_email_form (userena.tests.tests_forms.ChangeEmailFormTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bread-and-pepper/django-userena/userena/tests/tests_forms.py", line 181, in test_change_email_form
    invalid_dict['error'][1])
AssertionError: [u'Je staat al bekend onder dit e-maildres.'] != [u"You're already known under this email."]
```

**Comment by swistakm** [comment]
Possible case could be manipulating project settings inside tests without proper context manager.
