### ISSUE TITLE
Cannot start accounts app 

### ISSUE THREAD

**Issue by aramais** [bread-and-pepper/django-userena#473]
Following userena official docs I installed userena app, updated INSTALLED_APPS and AUTHNTIFICATION_BACKENDS. 

In order to define BaseProfile model, I need to create accounts app, but command 
python manage.py startapp accounts throws an error raise SiteProfileNotAvailable. 
Also when trying to create another app, or runserver I see the same error. Full text attached

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/userena/admin.py", line 30, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/usr/local/lib/python2.7/dist-packages/userena/utils.py", line 138, in get_profile_model
    raise SiteProfileNotAvailable
userena.compat.SiteProfileNotAvailable

This is kind of vicious cricle - in order to get rid of SiteProfileNotAvailable error I need to define a BaseProfile model in an accounts app which cannot be created. 
Tried to start app on another machine (currently working on Ubuntu 14, tried also on Kubuntu) - same problem.

**Comment by swistakm** [comment]
Sorry for such delay.

Have you solved your problem? If not I think you should create your new app (that you want to have profile model specified) before you include `userena` in `INSTALLED_APPS` settings variable. Then create new model and update `AUTH_PROFILE_MODULE` in settings. Finally include userena in `INSTALLED_APPS`

Also you can manually create app without need to use `./manage.py startapp`.

I'm not sure if this was the reason because I can't see your code but I hope it's that.

**Comment by aramais** [comment]
Hi!

Thanks for the reply. 
Sorry, I forgot to write thai I solved the issue right the way you said - I created accounts app and then installed userena.
