### ISSUE TITLE
startapp profiles error

### ISSUE THREAD

**Issue by marianobrc** [bread-and-pepper/django-userena#489]
Hello, i'm trying to use it with Django 1.8 and python 2.7.5 on virtualenv.

I'm just following all installation steps, and when i try to run:

python manage.py startapp accounts

I get the following error related to the definition of AUTH_PROFILE_MODULE. 

But i can't define it yet because the profile will be defined inside app's model, so how can i create the app avoiding this error?

/home/diremar/userna-venv/lib/python2.7/site-packages/userena/utils.py:133: RemovedInDjango19Warning: django.db.models.get_model is deprecated.
  profile_mod = get_model(*settings.AUTH_PROFILE_MODULE.rsplit('.', 1))

/home/diremar/userna-venv/lib/python2.7/site-packages/django/db/models/__init__.py:55: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from . import loading

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/userena/admin.py", line 30, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/home/diremar/userna-venv/lib/python2.7/site-packages/userena/utils.py", line 138, in get_profile_model
    raise SiteProfileNotAvailable
userena.compat.SiteProfileNotAvailable

Thanks, Regards

**Comment by swistakm** [comment]
Solution is simple:

0. remove userena from ``INSTALLED_APPS``
0. create app using ``python manage.py startapp accounts``
0. include``INSTALLED_APPS``
0. create your profile model and configure ``AUTH_PROFILE_MODULE``

This was already mentioned in #473 so I close it as duplicate.
