### ISSUE TITLE
"ImportError: cannot import name get_model" after update

### ISSUE THREAD

**Issue by alzearafat** [bread-and-pepper/django-userena#504]
Hi,

I just updating django-userena, the update process is successful, but when I try to run local server, it's error. Before update, it's working great. I'm using Django 1.8.x.

This is the traceback:

$ python manage.py runserver
```
Unhandled exception in thread started by <function wrapper at 0x7f21d11c4938>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/zea/Riset/Django-Project/gogotrip_env/gogotrip/accounts/models.py", line 4, in <module>
    from userena.models import UserenaBaseProfile
  File "/usr/local/lib/python2.7/dist-packages/userena/models.py", line 12, in <module>
    from userena.managers import UserenaManager, UserenaBaseProfileManager
  File "/usr/local/lib/python2.7/dist-packages/userena/managers.py", line 11, in <module>
    from userena.utils import generate_sha1, get_profile_model, get_datetime_now, \
  File "/usr/local/lib/python2.7/dist-packages/userena/utils.py", line 2, in <module>
    from django.db.models import get_model
ImportError: cannot import name get_model
```

Please advise. Thank you very much  :)

**Comment by rooney** [comment]
django.db.models.get_model is deprecated

See here for sample fix:
https://github.com/wq/django-swappable-models/issues/6

**Comment by indigodomo** [comment]
Still no fix for this bug? I don't want to go down the workaround path if there's a fix to userena...
