### ISSUE TITLE
get_profile_model not compatible with django 1.8

### ISSUE THREAD

**Issue by st8st8** [bread-and-pepper/django-userena#506]
I believe this line in utils/get_profile_model is not needed from django 1.8 where get_model and its ilk have been moved into the app loading system:

profile_mod = get_model(*settings.AUTH_PROFILE_MODULE.rsplit('.', 1))

Django then attempts this split again, which causes a LookupError because the appname is no longer there.

Create a new Userena app per the documentation against django 1.8 to reproduce.

**Comment by st8st8** [comment]
(this is the actual error)

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django_userena-1.4.1-py2.7.egg/userena/admin.py", line 30, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/usr/local/lib/python2.7/dist-packages/django_userena-1.4.1-py2.7.egg/userena/utils.py", line 138, in get_profile_model
    raise SiteProfileNotAvailable
userena.compat.SiteProfileNotAvailable
