### ISSUE TITLE
App registry error with Django 1.9

### ISSUE THREAD

**Issue by hadim** [bread-and-pepper/django-userena#519]
I am not sure if it's related to Django 1.9 (I didn't test with lower version) but I got the following error after following the installation instructions : 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/opt/conda/envs/django_app/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/userena/admin.py", line 31, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/userena/utils.py", line 132, in get_profile_model
    profile_mod = get_model(*settings.AUTH_PROFILE_MODULE.rsplit('.', 1))
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/apps/registry.py", line 196, in get_model
    app_label, model_name = app_label.split('.')
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by hadim** [comment]
After some digging, I disable all the userena related stuff and my server works. Now if I enable `userena` without anything else I have the following error : 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/conda/envs/django_app/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/userena/models.py", line 5, in <module>
    from django.contrib.sites.models import Site
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/contrib/sites/models.py", line 83, in <module>
    class Site(models.Model):
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
(django_app)root@7199ba359329:/srv/scimodel# pm check_permissions
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/opt/conda/envs/django_app/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/userena/admin.py", line 31, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/opt/conda/envs/django_app/lib/python3.5/site-packages/userena/utils.py", line 137, in get_profile_model
    raise SiteProfileNotAvailable
userena.compat.SiteProfileNotAvailable
```

And the error is still the same with `AUTH_PROFILE_MODULE = "scimodel.apps.accounts.models.ScimodelProfile"`

Any idea ?

**Comment by swistakm** [comment]
@hadim from what I see here the problem lies in the definition of `AUTH_PROFILE_MODULE` setting. Name of this variable is a bit misleading and the documentation is obviously imperfect. This should be obviously improved in future.
The correct syntax for this setting is: `app_name.ModelName`. So in your case it would be: `accounts.ScimodelProfile`.

**Comment by hadim** [comment]
Thank you. It works now !
