### ISSUE TITLE
Django 'patterns' deprecation bugging Guardian

### ISSUE THREAD

**Issue by bizzcat** [bread-and-pepper/django-userena#531]
```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/userena/models.py", line 10, in <module>
    from guardian.shortcuts import get_perms
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/guardian/shortcuts.py", line 14, in <module>
    from guardian.compat import str
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/guardian/compat.py", line 13, in <module>
    from django.conf.urls import url, patterns, include, handler404, handler500
ImportError: cannot import name 'patterns'
```

**I get the above terminal response when attempting to perform migration, runserver, etc...

I understand this is due to Django's deprecation of patterns, but I've gone to the python3.5/site-packages/guardian/compat.py file in questions and deleted patterns, but then this issue shows up:**
```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/userena/admin.py", line 31, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/Users/Kyo/development/news-agg/venv/lib/python3.5/site-packages/userena/utils.py", line 129, in get_profile_model
    raise SiteProfileNotAvailable
```

Wondering how far down the rabbit hole I need to go to make this work, and I'm a rather new developer so I assume there is a better way than what I know by default.

**Comment by bizzcat** [comment]
I uninstalled guardian and installed it again to get updated version. Then I uninstalled userena and installed it again. What happened is userena automatically re-installs the old guardian version, which is incompatible with the current Django version. [detailed below]

```
pip install django-userena
Collecting django-userena
  Using cached django_userena-2.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): html2text==2014.12.29 in ./venv/lib/python3.5/site-packages (from django-userena)
Collecting django-guardian<=1.4.1 (from django-userena)
Requirement already satisfied (use --upgrade to upgrade): easy-thumbnails in ./venv/lib/python3.5/site-packages (from django-userena)
Requirement already satisfied (use --upgrade to upgrade): six in ./venv/lib/python3.5/site-packages (from django-guardian<=1.4.1->django-userena)
Requirement already satisfied (use --upgrade to upgrade): Django>=1.7 in ./venv/lib/python3.5/site-packages (from django-guardian<=1.4.1->django-userena)
Requirement already satisfied (use --upgrade to upgrade): pillow in ./venv/lib/python3.5/site-packages (from easy-thumbnails->django-userena)
Installing collected packages: django-guardian, django-userena
  Found existing installation: django-guardian 1.4.5
    Uninstalling django-guardian-1.4.5:
      Successfully uninstalled django-guardian-1.4.5
Successfully installed django-guardian-1.4.1 django-userena-2.0.1
```



Also when I attempt to upgrade with this prompt `python manage.py django-guardian --upgrade
`, I get the same issue with patterns.

**Comment by bizzcat** [comment]
Nevermind ya'll, whence I got rid of the 'patterns' import, and did all of the fanaggling above, it worked. Migrations looked like this: 
```
python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, easy_thumbnails, guardian, news, sessions, sites
Running migrations:
  Rendering model states... DONE
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying guardian.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
```

**Comment by swistakm** [comment]
Reason for that situation is the fact that `django-guardian` dropped support for some of old Django versions that we still support in recent major release. We could not upgrade to newer guardian version without dropping backwards compatibility. We try to follow semantic versioning and apparently `django-guardian` does not.

We will eventually fix this in near future as next major release can declare new set of compatible Django releases. Anyway we were not ready to prepare new major release.

I reopen this since it is known issue that needs to be fixed somehow eventually.

**Comment by dacodekid** [comment]
@bizzcat I just ran into the same issue but got it resolved with the following steps.

* `pip install django-userena` (installs `Guardian` 1.4.1)
* `pip install django-guardian --upgrade` (installs `Guardian` 1.4.5)

The `SiteProfileNotAvailable` error is due to lack of a `Profile` model in your [`accounts`](http://django-userena.readthedocs.io/en/latest/installation.html#profiles) app?!

**Comment by alzearafat** [comment]
Is this already solved? Because I just ran the same problem. @swistakm

**Comment by swistakm** [comment]
I think that the easiest solution to this problem would be to:
* bump guardian requirement version (newest version supports only django1.7+)
* drop support for django1.5 & django1.6 (because of guardian dependency)
* resolve any problems that occur
* release userena as 3.0.0 (because of backward incompatible changes)

Unfortunately, I had completely different plans for 3.x release. I wanted to:
* get rid of unused stuff
* replace function based views with class based ones for better modularity
* do some other improvements that required backwards incompatible changes

And actually this was a plan for 2.x that we had to postpone from similar reasons. We can do that again.

Personally, I think that the best would be if we could do the following in next major release:
* completely get rid of guardian dependency and remove object based permissions from the project as the only increase complexity and not many people tend to use them
* remove umessages from the project from similar reason
* add all improvements planed previously for next major release (CBV, et al.) 
* choose some sane coding standard for the project as it currently lacks any

But in result we would get a completely different piece of software. But maybe this is what userena needs now - focusing on things that really matter instead of doing everything.

Still, this is not something that I can do all by myself.

**Comment by meberli** [comment]
same issue here..

**Comment by dcolumbus** [comment]
I don't know what's happening with this but after running `pip install django-guardian --upgrade` I now get:

```
File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/userena/admin.py", line 31, in <module>
    admin.site.register(get_profile_model(), GuardedModelAdmin)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/userena/utils.py", line 129, in get_profile_model
    raise SiteProfileNotAvailable
userena.compat.SiteProfileNotAvailable
```

**Comment by bashu** [comment]
@dcolumbus django-guardian==1.4.2 works just fine

**Comment by pm5** [comment]
Some issue with @dcolumbus here.  I'm using:

Django==1.10.6
django-guardian==1.4.2
django-userena==2.0.1

**Comment by extant1** [comment]
Still no fix for this?
